language: node_js

node_js:
  - '8'

cache:
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh

script:
  - yarn ci-check

notifications:
  email: false
